version: "3.1"

services: 
  locust:
    build: .
    environment: 
      - LOCUST_PARAMS=10
      - LOCUST_TARGET_HOST=http://34.74.132.61:8070
      - LOCUST_MODE=master
    ports: 
      - "8089:8089"
