apiVersion: v1
kind: Service
metadata:
  name: locust-master-deployment
  labels:
    name: locust
spec:
  type: LoadBalancer
  selector:
    name: locust
    role: master  
  ports:
    - port: 8089
      protocol: TCP
      name: master-web
    - port: 5557
      protocol: TCP
      name: master-port1
    - port: 5558
      protocol: TCP
      name: master-port2
